### ISSUE TITLE
Add automated github actions go binary build

### ISSUE THREAD

**Issue by vallezw** [SheetAble/SheetAble#11]
Implement automation for building the go binaries via Github Actions (**CGO_ENABLED** has to be enabled for the binary to work).
A different approach would be building the go binaries with Docker and then automating that image in the GitHub Actions process.

**Comment by jj-style** [comment]
Hey! I'll give this a shot if that's okay?

Just to check, would you like the run conditions for building and releasing to be the same as the docker github action?
So pushes with tags `v*` should trigger a build and release of the go binary for windows, mac and linux?

**Comment by vallezw** [comment]
Hey! I've been struggling with this issue already a bit, but didn't get it to work properly. I have planned it to go exactly like you explained above, so it'd be a great help if you could get it to work.

Thanks a lot!

**Comment by vallezw** [comment]
Hey! I wanted to tell you that you should be sure to build it with CGO_ENABLED=1 as an env var since you need CGO for the SQLite drivers. And I don't know how far you've gotten, but maybe this [build-commands.md](https://github.com/SheetAble/SheetAble/blob/master/build-commands.md) file can help you on the way

**Comment by jj-style** [comment]
Cheers I hadn't gotten started yet but that looks very helpful, thank you! I'll try to have something working by the end of the weekend :crossed_fingers:
