### ISSUE TITLE
Docker multi-architecture builds

### ISSUE THREAD

**Issue by jj-style** [SheetAble/SheetAble#15]
Build docker containers for multiple architectures (e.g. arm and amd64) so the docker image can be run on more devices like raspberry pi's which are often used to selfhost services. 

**Describe the solution you'd like**
As part of automated docker build and push github action, use `docker buildx` to create images for other architectures

**Describe alternatives you've considered**
Building the binary in a custom docker container on a raspberry-pi so it can be run on the arm chip

It looks like there is some mention of `buildx` already in the `build` workflow so it might nearly be there!

**Comment by vallezw** [comment]
Hey! Thanks for the issue. I have also been looking into that issue that we currently only have the mac and windows binaries and it's pretty annoying. I definitely want to automate that process over the GitHub actions. However, I already tried that a few times and didn't get it to work right now. So I guess I would have to try that again sometime soon. I will be focusing on the feature enhancements right now though. If you are already familiar with GitHub actions and how to build go projects you could give it a try if you want to. Let me know if you would want to do it or if I should assign myself to this issue.

**Comment by vallezw** [comment]
Alright cool! Thanks a lot. I'll assign you to this issue then.

**Comment by jj-style** [comment]
Nice one, thank you! :)
