### ISSUE TITLE
Unknown Composer

### ISSUE THREAD

**Issue by marcus-k** [SheetAble/SheetAble#23]
New user, love the project so far. I have noticed on my first usage of the app when uploading a sheet for the first time and adding a new composer, then proceeding to delete the newly created composer, makes the new composer of the sheet "Unknown". 

![image](https://user-images.githubusercontent.com/81660172/147172294-818d7b33-543a-4d16-bb0f-33b557f35a4a.png)

Further, after deleting the sheet, this "Unknown" composer cannot be deleted and is stuck listed in the Composer tab. That is, the deleted button does not work.

![image](https://user-images.githubusercontent.com/81660172/147172319-a3933983-6239-4a17-bce8-f756862dcba9.png)

**Comment by vallezw** [comment]
Alright, thanks for reporting the bug. I'll try to get on it as soon as I can.
