### ISSUE TITLE
More Unknown Composer

### ISSUE THREAD

**Issue by marcus-k** [SheetAble/SheetAble#24]
Just discovered this after the hotfix of #23 by doing the reverse procedure I mentioned there. Uploading a sheet for the first time with a new composer, deleting the sheet, then deleting the composer, results in the same Unknown composer bug as before.

I would ideally help and find these bugs in the code too, but alas, I do not have any Go experience myself.

**Comment by vallezw** [comment]
Alright I'll look into it as soon as I can.
