### ISSUE TITLE
User Management in Settings

### ISSUE THREAD

**Issue by Drumhavoc** [SheetAble/SheetAble#26]
**Is your feature request related to a problem? Please describe.**
I cannot see which users I have invited and which I haven't and more importantly, I cannot delete users no longer needed.  I created some users one accident and don't have anyway to terminate the connection they have.

**Solution I would like to see**
I would like to have a user management interface in the setting that can show all users that have access to my site, and include the follow options/information:
1. Delete User
2. User Role (Admin, Power User, Viewer)
3. Last Login
4. Number of Uploads/Downloads?
The User roles would be nice as well as some users I only want to view/download the music but not upload anything and others I would like to have normal use.  Those roles can be broken down differently but the basic idea would be really nice to have.
Thinks like the Last Login or the Number of Uploads/Downloads would just be some nice statics to know how engaged my users actually are but aren't necessary if they are a lot of extra work.

Main thing is a visual to see who as access to the site and a way to easily remove/delete that access.

Thanks for all the hard work!

**Comment by vallezw** [comment]
Alright, this new feature requires backend and frontend work. Making it two separate tasks:

- [ ] Add backend compatibility for listing users and their roles etc
- [ ] Add frontend visualization for backend endpoints

**Comment by vallezw** [comment]
Hey @Drumhavoc sry for being so inactive in the development. However now I am full on again and going to actively keep on developing on the tablet client as well as the web app. Now coming to this issue I wanted to know if I should make the users management in a separate web page or directly in the settings page what do you think?

**Comment by Drumhavoc** [comment]
Maybe as its own tab in the settings?
![Screenshot_2022-07-01-00-57-55-609](https://user-images.githubusercontent.com/40368327/176826522-05300195-8ecd-4423-89f3-df771e961783.png)
Something like this maybe but with email connection

**Comment by vallezw** [comment]
Yes it'll probably look that way afterwards, when I add more setting options. For now if you are an admin, you see a users table directly on the settings screen.
