### ISSUE TITLE
Prebuild Binaries

### ISSUE THREAD

**Issue by nephaste** [SheetAble/SheetAble#35]
Hello thanks for this application

I actually integrate Sheetable inside Qnap NAS with Qnapclub

is it possible to have more precompiled Linux architecture in githug released page

- ARMv5
- ARMv7
- ARM64
- x86 (32bit)

thanks a lot, this will be helpfull for many people

**Comment by vallezw** [comment]
Alright I'll try implementing them in the next few weeks.

**Comment by vallezw** [comment]
Hey, @jj-style, I tried implementing it, but installing the arm64 libraries somehow doesn't work, etc. Do you think you could take a look at it? (https://github.com/vallezw/SheetAble) that's my fork where I tried testing it on the main branch.

**Comment by jj-style** [comment]
Hey, yeah happy to take a look at it. Will have to be in the next week or two if that's alright

**Comment by vallezw** [comment]
Awesome thanks a lot!
