### ISSUE TITLE
Failing to update from v0.6.4 to v0.8.0

### ISSUE THREAD

**Issue by marcus-k** [SheetAble/SheetAble#49]
Been a little while since I had a chance to take a look at the project again. Was on an older version of SheetAble (v0.6.4) and decided to update to the latest version (v0.8.0). Does not look like the update is working however. I am getting the following errors:

```
  ______   __                             __       ______   __        __           
 /      \ |  \                           |  \     /      \ |  \      |  \          
|  $$$$$$\| $$____    ______    ______  _| $$_   |  $$$$$$\| $$____  | $$  ______  
| $$___\$$| $$    \  /      \  /      \|   $$ \  | $$__| $$| $$    \ | $$ /      \ 
 \$$    \ | $$$$$$$\|  $$$$$$\|  $$$$$$\\$$$$$$  | $$    $$| $$$$$$$\| $$|  $$$$$$\
 _\$$$$$$\| $$  | $$| $$    $$| $$    $$ | $$ __ | $$$$$$$$| $$  | $$| $$| $$    $$
|  \__| $$| $$  | $$| $$$$$$$$| $$$$$$$$ | $$|  \| $$  | $$| $$__/ $$| $$| $$$$$$$$
 \$$    $$| $$  | $$ \$$     \ \$$     \  \$$  $$| $$  | $$| $$    $$| $$ \$$     \
  \$$$$$$  \$$   \$$  \$$$$$$$  \$$$$$$$   \$$$$  \$$   \$$ \$$$$$$$  \$$  \$$$$$$$ v0.8

Connected to sqlite database /app/config/database.db...
2022/08/15 11:24:50 cannot migrate table: Cannot add a UNIQUE column
```
There are no further messages in the log besides this. 

Perhaps it's just a simple fix and I just did something dumb, or there are breaking changes between versions that make updating impossible. I'm not sure, would be open to hearing more.

**Comment by vallezw** [comment]
Yeah sorry about that. There were database changes in a new version which doesn't make it possible to update from these. Unfortunately I don't have a lot of time right now, but my plan is to fix that thing in the next version so stuff like that could never happen again. Im going to rewrite the file structure etc.

So you could just go back to v0.6 and it should work fine or you have to upload the Sheets again in v0.8. Sorry again for the troubles.

**Comment by marcus-k** [comment]
Ah okay, no worries. I've mainly been testing out features and stuff rather than trying to move all my sheet music to it, so there isn't much loss. Looking forwards to the file structure update in the future.
