### ISSUE TITLE
Chinese Composer and Sheet Name not supported

### ISSUE THREAD

**Issue by SheepYY039** [SheetAble/SheetAble#55]
**Describe the bug**
Sheetable does not support uploading sheets with Chinese (and non-lain characters?) sheet name or composer name. 

**To Reproduce**
1. Go to Upload
2. Enter Chinese Sheet Name (e.g. 老男孩)
3. Enter Chinese Composer (e.g. 大桥卓弥)
4. Upload sheet 
5. See error
    1. Sheet Thumbnail does not get generated 
    2. when clicked, redirects to <http[s]://[domain]:[port]/sheet//> which returns page not found error
    3. Similar result when clicking on composer thumbnail

**Expected behavior**
It is expected that a sheet thumbnail is generated, that upon clicking on the sheet thumbnail, goes to the sheet or composer details page. 

**Screenshots**

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56354081/211778845-26d7086f-f2e3-4c90-8b34-8ad031079183.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56354081/211778939-e2176b1a-931f-4120-9374-86b8d5e3729d.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Firefox 
 - Version [e.g. 22] Not sure

**Smartphone (please complete the following information):**

**Additional context**
For most non-Latin characters, they have corresponding Latin character groups that represent them, for example, each Chinese character has their corresponding Pinyin which represents the character's pronunciation. Usually, applications will either 
1. directly implement and show the non-Latin character, or 
2. they will show the non-Latin character, but store its corresponding Latin version in the database, or 
3. convert the non-Latin character into its Latin version, and show and store that (however, there could be a problem if two different composers have different names but same pronunciation, the database might misidentify it as the same person if name is used as the identifying property)

**Comment by vallezw** [comment]
Alright I’ll look into it this weekend

**Comment by vallezw** [comment]
Hey @SheepYY039 I fixed the issue it is currenlty being pushed on dockerhub version v0.8.1 . Can you tell me if its working for you now?

**Comment by SheepYY039** [comment]
I see that you've asked me to check it on docker hub v0.8.1 but I think the docker build failed for this version?

**Comment by vallezw** [comment]
Hey yeah the fix is finished. But somehow the docker push was broken so I deleted the release. I’ll try to fix it today or tomorrow then you can test it

**Comment by vallezw** [comment]
Alright the v0.8.1 build is pushing now. Everything should be working now. Would you mind testing it and telling me if it works for you @SheepYY039?
