### ISSUE TITLE
Hello iam new please help me

### ISSUE THREAD

**Issue by Bilal-Ahmed-Developer** [SheetAble/SheetAble#58]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bilal-Ahmed-Developer** [comment]
iam a new front end developer please guide me how to contribute

**Comment by vallezw** [comment]
Hey @Bilal-Ahmed-Developer, thanks for the interest. There is a development and contributions guide on the [website](https://sheetable.net/docs/development). If you don’t know already what you want to work on, take a look at the [issues](https://github.com/SheetAble/SheetAble/issues)
