### ISSUE TITLE
Share Button not working

### ISSUE THREAD

**Issue by Portagoras** [SheetAble/SheetAble#67]
**Describe the bug**
When you click the share button it says "copied" but it hasn't actually put it into your clipboard

**To Reproduce**
1. Go to a sheet in your library
2. Click on 'Share'
3. Check your clipboard

**Expected behavior**
A link to the sheet is put into your clipboard.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox 114.0.2 (64-Bit)
 - Sheetable Version v0.8.1

**Console Error**
Uncaught TypeError: navigator.clipboard is undefined
    onClick Sheet.js:209

**Comment by Nabeelcodes110** [comment]
I am working on this 🙌

**Comment by vallezw** [comment]
Thanks, the ci has to run through and then I can merge it [#69](https://github.com/SheetAble/SheetAble/pull/69)
